#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_RESEARCH_USER}') THEN
        CREATE ROLE ${APP_RESEARCH_USER} LOGIN PASSWORD '${APP_RESEARCH_PASSWORD}';
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_TRADER_USER}') THEN
        CREATE ROLE ${APP_TRADER_USER} LOGIN PASSWORD '${APP_TRADER_PASSWORD}';
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_RESEARCH_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_TRADER_USER};

GRANT USAGE, CREATE ON SCHEMA public TO ${APP_RESEARCH_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${APP_TRADER_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_RESEARCH_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_TRADER_USER};

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${APP_RESEARCH_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${APP_TRADER_USER};

-- Objects created by postgres during init
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_RESEARCH_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_TRADER_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_RESEARCH_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_TRADER_USER};

-- Objects created at runtime by the research app role
ALTER DEFAULT PRIVILEGES FOR ROLE ${APP_RESEARCH_USER} IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_TRADER_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${APP_RESEARCH_USER} IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO ${APP_TRADER_USER};
EOSQL
