#!/bin/sh
# Shared NOLOGIN role so research_user and trader_user can both run init_db()
# (CREATE INDEX, etc.) via DATABASE_APP_ROLE=abc_app in app .env — see docs.
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'abc_app') THEN
        CREATE ROLE abc_app NOLOGIN;
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO abc_app;
GRANT USAGE, CREATE ON SCHEMA public TO abc_app;

GRANT abc_app TO ${APP_RESEARCH_USER};
GRANT abc_app TO ${APP_TRADER_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE abc_app IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_RESEARCH_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE abc_app IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_TRADER_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE abc_app IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_RESEARCH_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE abc_app IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_TRADER_USER};
EOSQL
