"""Load and merge deployment environment profiles (paper / live / dev)."""

from __future__ import annotations

from pathlib import Path

PROFILES_DIR = Path(__file__).resolve().parent / "env"
VALID_ENVS = frozenset({"paper", "live", "dev"})


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines; ignore comments and blanks."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if not key:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        out[key] = value
    return out


def resolve_profile_path(env_name: str) -> Path:
    """Prefer gitignored ``{env}.env``; fall back to committed ``{env}.env.example``."""
    env_name = env_name.strip().lower()
    if env_name not in VALID_ENVS:
        raise ValueError(f"Unknown env {env_name!r}; expected one of {sorted(VALID_ENVS)}")
    local = PROFILES_DIR / f"{env_name}.env"
    if local.is_file():
        return local
    example = PROFILES_DIR / f"{env_name}.env.example"
    if example.is_file():
        return example
    raise FileNotFoundError(f"No profile for {env_name!r} under {PROFILES_DIR}")


def merge_env_files(*paths: Path) -> dict[str, str]:
    """Later files override earlier keys."""
    merged: dict[str, str] = {}
    for path in paths:
        merged.update(parse_env_file(path))
    return merged


def write_env_file(path: Path, values: dict[str, str]) -> Path:
    """Write merged env for docker compose ``--env-file``."""
    lines = [
        "# Generated by infra/deploy.py — do not commit secrets here.",
        "# Re-run deploy to refresh profile merge.",
        "",
    ]
    for key in sorted(values):
        val = values[key]
        if any(c.isspace() for c in val) or "#" in val:
            val = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{val}"')
        else:
            lines.append(f"{key}={val}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def build_deploy_env(
    repo_root: Path,
    env_name: str,
    *,
    extra_paths: tuple[Path, ...] = (),
) -> tuple[Path, dict[str, str]]:
    """Merge profile + repo ``.env`` (+ optional extras) into ``.env.deploy``."""
    profile = resolve_profile_path(env_name)
    paths: list[Path] = [profile, *extra_paths]
    dotenv = repo_root / ".env"
    if dotenv.is_file():
        paths.append(dotenv)
    merged = merge_env_files(*paths)
    out = repo_root / ".env.deploy"
    write_env_file(out, merged)
    return out, merged
